<?php

if ($this->session->isAdmin == 0) {
    // Retrieve its value
    $nama = $this->session->nama_user;

    echo "<h2>Welcome to Lammas, " . $nama . "!<h2>";
    echo $this->tag->linkTo(["/pengguna/logout", "Logout", 'class' => 'btn btn-warning']);
    ?>
    <div class="box col-md-6">
        <h5>Menu</h5>
        <ul>
            <li><?php echo $this->tag->linkTo("/mahasiswa/reservasipcpage", "Reservasi PC"); ?>
            <li><?php echo $this->tag->linkTo("/mahasiswa/jadwalpemakaianruangan", "Melihat jadwal pemakaian lab"); ?>
        </ul>
    </div>

<?php    
}
else {
    echo "You must login to see this page";
    header("refresh:2;url=/pengguna/loginpage");
} ?>

<style>
h2{
    margin:20px;
    text-align:left;
}
li{
    font-size:22px;
}
body{
    background-image: url("<?php echo $this->url->get('img/Lammas_Logo.png')?>");
    background-repeat: no-repeat;
    background-position: center;height: 500px;
}
</style>