<?php

if ($this->session->isAdmin == 0) {
    ?>
    <div class="box col-md-6">
        <!-- <h5>Menu</h5>
        <ul>
            <li><?php echo $this->tag->linkTo("/mahasiswa/reservasipcpage", "Reservasi PC"); ?>
            <li><?php echo $this->tag->linkTo("/mahasiswa/jadwalpemakaianruangan", "Melihat jadwal pemakaian lab"); ?>
        </ul> -->
    </div>

<?php    
}
else {
    echo "You must login to see this page";
    header("refresh:2;url=/pengguna/loginpage");
} ?>
