<div class="box col-sm-6">
    <?php
    echo $this->tag->form("/mahasiswa/jadwallab");
    // echo "<h5> Lihat jadwal lab <h5>";
    echo $form->render('lab');
    echo $this->tag->submitButton(["Lihat!", 'class' => 'btn btn-primary', 'style' => 'margin-left: 1pc;']);
    // echo "</br></br>".$this->tag->linkTo("/mahasiswa/dashboard", " Kembali");
    ?>
    </form>
</div>

<style>
body {
    /* background-color: #E5E9EC; */
    text-align: center;
    margin:auto;
}

.box{
      background-color: white;
      box-shadow: 0px 10px 8px #888888;
      border-radius: 15px;
      padding-right: 100px;
      text-align: right;
      padding-top: 20px;
      padding-bottom: 20px;
      margin:auto;
      float:none;
}

.page-header{
      margin:auto;
}
</style>