<?php
if($this->session->has('nama_user')){
    // $id = $this->session->get('user_id');
    ?>
    <!-- <h3>Daftar Inventaris</h3> -->
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
            <tr>
                <th>Nomor</th>
                <th>Nama</th>
                <th>Status</th>
                <th>Lab</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($invens as $inven) { ?>
            <tr>
                <td class="counterCell"></td>
                <td><?php echo $inven->nama_barang; ?></td>
                <td><?php echo $inven->status; ?></td>
                <td><?php echo $inven->nama_lab; ?></td>
                <td>
                    <?php
                    if ($inven->status == "unavailable"){
                        echo $this->tag->linkTo([
                            // "/mahasiswa/". implode("",$id) . "/listInv",
                            "/mahasiswa/listInv/" . $id,
                            "Request",
                            'class' => 'btn btn-secondary btn-block'
                        ]);
                    }else{
                        echo $this->tag->linkTo([
                            "/mahasiswa/requestInv/". $id . "/" . $inven->id,
                            "Request",
                            'class' => 'btn btn-primary btn-block'
                        ]);
                    }
                    ?>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
} ?>


<style>
body {
    /* background-color: #E5E9EC; */
    text-align: center;
    margin:auto;
}
.thead-blu {
    background-color:#c7e8f3;
}
.box{
      background-color: white;
      box-shadow: 0px 10px 8px #888888;
      border-radius: 15px;
      /* padding-right: 80px; */
      text-align: center;
      /* padding-top: 20px;
      padding-bottom: 20px; */
      /* padding:20px 50px; */
      margin:auto;
      float:none;
}
.page-header{
      margin:auto;
}
</style>