<?php
if ($this->session->isAdmin) {
    ?>
    <div class="box col-md-12 text-center">
        <!-- <div class="container" style="margin-left: 50px"> -->
        <div class="container">
            <div class="card-deck mb-4 text-center">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Pinjam Inventaris</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title"><?php echo $jPinjInvs; ?></h1>
                        <?php
                            echo $this->tag->linkTo([
                                "/admin/listpeminjamanInv/".$this->session->isAdmin,
                                "Pergi Ke Halaman",
                                'class' => 'btn btn-lg btn-outline-primary'
                            ]);
                        ?>
                    </div>
                </div>
                <div class="card mb-4 box-shadow">
                <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Reservasi PC</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title"><?php echo $jPinjPcs; ?></h1>
                        <?php
                            echo $this->tag->linkTo([
                                "/admin/listReservasiPc/",
                                "Pergi Ke Halaman",
                                'class' => 'btn btn-lg btn-outline-primary'
                            ]);
                        ?>
                    </div>
                </div>
                <div class="card mb-4 box-shadow">
                <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Reservasi Ruangan</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title"><?php echo $jPinjLabs; ?></h1>
                        <?php
                            echo $this->tag->linkTo([
                                "/admin/listPermohonanRuangan/".$this->session->isAdmin,
                                "Pergi Ke Halaman",
                                'class' => 'btn btn-lg btn-outline-primary'
                            ]);
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php    
}
else {
    echo "Who are you?";
    header("refresh:2;url=/pengguna/loginpage");
} ?>


<style>
body {
    /* background-color: #E5E9EC; */
    /* text-align: center; */
    margin:auto;
}
.thead-blu {
    background-color:#c7e8f3;
}
.box{
      background-color: white;
      box-shadow: 0px 10px 8px #888888;
      border-radius: 15px;
      /* padding-right: 80px; */
      text-align: center;
      /* padding-top: 20px;
      padding-bottom: 20px; */
      /* padding:20px 50px; */
      margin:auto;
      float:none;
}
.page-header{
      margin:auto;
}
</style>