<?php

if ($this->session->isAdmin) { ?>
    <!-- <h2>Form Edit PC</h2> -->
    <div class="box col-sm-6">
        <?php echo $this->tag->form("/admin/updatePC/".$id); ?>

            <p>
                <label for="nama">Nama</label>
                <?php echo $this->tag->textField(['nama', 'value' => $nama]); ?>
            </p>

            <p>
                <label for="ip">IP</label>
                <?php echo $this->tag->textField(['ip', 'value' => $ip]); ?>
            </p>

            <p>
                <label for="hdd">Ukuran Hardisk</label>
                <?php echo $this->tag->textField(['hdd', 'value' => $hdd]) ?>
            </p>

            <p>
                <label for="ram">RAM</label>
                <?php echo $this->tag->textField(['ram', 'value' => $ram]); ?>
            </p>

            <p>
                <label for="processor">Processor</label>
                <?php echo $this->tag->textField(['processor', 'value' => $processor]); ?>
            </p>

            <p>
                <label for="gpu">GPU</label>
                <?php echo $this->tag->textField(['gpu', 'value' => $gpu]); ?>
            </p>

            <p>
                <label for="status">Status</label>
                <?php echo $this->tag->textField(['status', 'value' => $status]); ?>
            </p>
            
            <div class="d-flex justify-content-between" style="padding-top : 1pc">
                <?php echo $this->tag->linkTo(
                    [
                        "/admin/listPC/",
                        "Kembali",
                        'class' => 'btn btn-primary',
                    ]); ?>
                <?php echo $this->tag->submitButton(["Ubah!", 'class'=>'btn btn-success']); ?>
            </div>
    </form>
</div>

<?php    
}
else {
    echo "Who are you?";
    header("refresh:2;url=/pengguna/loginpage");
} ?>

<style>
body {
    /* background-color: #E5E9EC; */
    /* text-align: center; */
    margin:auto;
}

.box{
      background-color: white;
      box-shadow: 0px 10px 8px #888888;
      border-radius: 15px;
      padding-right: 100px;
      text-align: right;
      padding-top: 20px;
      padding-bottom: 20px;
      margin:auto;
      float:none;
}

.page-header{
      margin:auto;
}
</style>