<?php
if ($this->session->has('isAdmin')) {
    // Retrieve its value
    // $id = implode("",$this->session->get('isAdmin'));
    $id = $this->session->get('isAdmin');
    echo $this->tag->linkTo(["/admin/".$this->session->isAdmin."/createInv", "Tambah Inventaris", "class"=>"btn btn-primary"]);
    ?>
    <!-- <h3>Inventaris</h3> -->
    <table class="table table-bordered table-hover">
        <thead class="text-center thead-light">
            <tr>
                <th style="width:10%">Nomor</th>
                <th style="width:25%">Nama</th>
                <th style="width:25%">Status</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        <?php
        if ($invens->count() > 0) {
            foreach ($invens as $inven) { ?>
            <tr>
                <td class="counterCell"></td>
                <td><?php echo $inven->nama_inv; ?></td>
                <td><?php echo $inven->status_inv; ?></td>
                <td>
                    <div class="d-flex justify-content-around">
                        <?php
                            echo $this->tag->linkTo([
                                // "/admin/".$id."/updateInv/".$inven->id_inv,
                                "/admin/updateInv/".$id."/".$inven->id_inv,
                                "Edit",
                                'class' => 'btn btn-info',
                                'style' => 'width:110px'
                            ]);
                        ?>
                        <?php
                            echo $this->tag->linkTo([
                                // "/admin/".$id."/deleteInv/".$inven->id_inv,
                                "/admin/deleteInv/".$id."/".$inven->id_inv,
                                "Delete",
                                'class' => 'btn btn-danger',
                                'style' => 'width:110px'
                            ]);
                        ?>
                    </div>
                </td>
            </tr>
        <?php } 
        }else{ 
            ?>
            <tr>
                <td colspan="5"><p class="text-center">Bersiihh, tidak ada barang~</p></td>
            </tr>
            <?php
        } ?>
        </tbody>
    </table>
<?php } ?>

<style>
body {
    /* background-color: #E5E9EC; */
    margin:auto;
}
.thead-blu {
    background-color:#c7e8f3;
}
.box{
      background-color: white;
      box-shadow: 0px 10px 8px #888888;
      border-radius: 15px;
      /* padding-right: 80px; */
      text-align: center;
      /* padding-top: 20px;
      padding-bottom: 20px; */
      /* padding:20px 50px; */
      margin:auto;
      float:none;
}
.page-header{
      margin:auto;
}
</style>