<div class="box col-md-6">
    <?php
    if ($this->session->has('isAdmin')) {
        // $id = implode("",$this->session->get('isAdmin'))
        $id = $this->session->get('isAdmin');
        ?>
        <!-- <h3 style = "padding-bottom : 30px">Menambah Inventaris</h3> -->

        <?php echo $this->tag->form("inventaris/submit/".$id); ?>
            
            <p>
                <label for="nama" style="width: 150px">Nama</label>
                <?php echo $this->tag->textField("nama"); ?>
            </p>
            <p>
                <label for="status" style="width: 150px">Status</label>
                <?php echo $this->tag->textField("status"); ?>
            </p>
            <div class="d-flex justify-content-between" style="padding-top : 2pc">
            <!-- <div class="d-flex justify-content-right" style="padding-top : 2pc"> -->
                <?php echo $this->tag->linkTo(
                    [
                        "/admin/".$this->session->isAdmin."/listInv",
                        "Kembali",
                        'class' => 'btn btn-primary',
                    ]); ?>
                <?php echo $this->tag->submitButton(
                    [
                        "Submit",
                        'class' => 'btn btn-success',
                    ]); ?>
            </div>

        </form>
    <?php 
    }else{
        echo "Sorii, hanya admin yang boleh mengakses halaman ini :)";
        header( "refresh:2;url=/" );
    }

    ?>
</div>

<style>
body {
    /* background-color: #E5E9EC; */
    /* text-align: center; */
    margin:auto;
}
.thead-blu {
    background-color:#c7e8f3;
}
.box{
      background-color: white;
      box-shadow: 0px 10px 8px #888888;
      border-radius: 15px;
      /* padding-right: 80px; */
      text-align: center;
      /* padding-top: 20px;
      padding-bottom: 20px; */
      padding:20px 50px;
      margin:auto;
      float:none;
}
</style>