<?php
if ($this->session->has('nama_user')) {

    // echo "<h5>Jadwal Ruangan Lab " . $namalab . "<h5>";
    if(!$this->session->isAdmin) {   
        echo $this->tag->linkTo("/mahasiswa/reservelabpage", "Reservasi lab")."</br>";
    }
    /*if($this->session->isAdmin) {   
        echo $this->tag->linkTo("/admin/dashboard", "Kembali ke dashboard");
    } else {
        echo $this->tag->linkTo("/mahasiswa/jadwalpemakaianruangan", "Kembali");
    }*/ ?>

    <div class="box col-md-10">
        <?php foreach ($prs as $pr) { ?>
        <table class="table table-bordered table-hover">
            <thead class="thead-blu">
            <tr>
                <th>#</th>
                <th>Waktu</th>
                <th>Keperluan</th>
            </tr>
            </thead>
            <tbody>
            <?php 
            $i=1;
            foreach ($prs as $pr) { ?>
                <tr>
                    <td><?php echo $i; ?></td>
                    <td><?php echo $pr->tanggal; ?></td>
                    <td><?php echo $pr->keperluan; ?></td>

                </tr>
            <?php $i++; } ?>
            </tbody>
        </table>
    </div>
    <?php    
    }
}
else {
echo "You must login to see this page";
header("refresh:2;url=/pengguna/loginpage");
} ?>

<style>
body {
    /* background-color: #E5E9EC; */
    margin:auto;
}
.thead-blu {
    background-color:#c7e8f3;
}
.box{
      background-color: white;
      box-shadow: 0px 10px 8px #888888;
      border-radius: 15px;
      /* padding-right: 80px; */
      text-align: center;
      /* padding-top: 20px;
      padding-bottom: 20px; */
      padding:20px 50px;
      margin:auto;
      float:none;
}
.page-header{
      margin:auto;
}
</style>