<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Lammas</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <!-- <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/> -->
        <link rel="shortcut icon" type="image/png" href="<?php echo $this->url->get('img/Lammas_Logo.png')?>"/>
        <link rel="stylesheet" href="<?php echo $this->url->get('css/mycss.css')?>">


        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" href="images/favicon.ico" type="image/ico" />

        <title>Gentelella Alela! | </title>

        <!-- Bootstrap -->
        <link href="<?php echo $this->url->get('gentelella-master/vendors/bootstrap/dist/css/bootstrap.min.css'); ?>" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="<?php echo $this->url->get('gentelella-master/vendors/font-awesome/css/font-awesome.min.css'); ?>" rel="stylesheet">
        <!-- NProgress -->
        <link href="<?php echo $this->url->get('gentelella-master/vendors/nprogress/nprogress.css'); ?>" rel="stylesheet">
        <!-- iCheck -->
        <link href="<?php echo $this->url->get('gentelella-master/vendors/iCheck/skins/flat/green.css'); ?>" rel="stylesheet">
      
        <!-- bootstrap-progressbar -->
        <link href="<?php echo $this->url->get('gentelella-master/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css'); ?>" rel="stylesheet">
        <!-- JQVMap -->
        <link href="<?php echo $this->url->get('gentelella-master/vendors/jqvmap/dist/jqvmap.min.css'); ?>" rel="stylesheet"/>
        <!-- bootstrap-daterangepicker -->
        <link href="<?php echo $this->url->get('gentelella-master/vendors/bootstrap-daterangepicker/daterangepicker.css'); ?>" rel="stylesheet">

        <!-- Custom Theme Style -->
        <link href="<?php echo $this->url->get('gentelella-master/build/css/custom.min.css'); ?>" rel="stylesheet">
    </head>
    <body>
        <!-- <div class="container"> -->
            <?php echo $this->getContent(); ?>
        <!-- </div> -->
        <!-- jQuery first, then Popper.js, and then Bootstrap's JavaScript -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    
    
        <!-- jQuery -->
        <script src="<?php echo $this->url->get('gentelella-master/vendors/jquery/dist/jquery.min.js'); ?>"></script>
    <!-- Bootstrap -->
    <script src="<?php echo $this->url->get('gentelella-master/vendors/bootstrap/dist/js/bootstrap.bundle.min.js'); ?>"></script>
    <!-- FastClick -->
    <script src="<?php echo $this->url->get('gentelella-master/vendors/fastclick/lib/fastclick.js'); ?>"></script>
    <!-- NProgress -->
    <script src="<?php echo $this->url->get('gentelella-master/vendors/nprogress/nprogress.js'); ?>"></script>
    <!-- Chart.js -->
    <script src="<?php echo $this->url->get('gentelella-master/vendors/Chart.js/dist/Chart.min.js'); ?>"></script>
    <!-- gauge.js -->
    <script src="<?php echo $this->url->get('gentelella-master/vendors/gauge.js/dist/gauge.min.js'); ?>"></script>
    <!-- bootstrap-progressbar -->
    <script src="<?php echo $this->url->get('gentelella-master/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js'); ?>"></script>
    <!-- iCheck -->
    <script src="<?php echo $this->url->get('gentelella-master/vendors/iCheck/icheck.min.js'); ?>"></script>
    <!-- Skycons -->
    <script src="<?php echo $this->url->get('gentelella-master/vendors/skycons/skycons.js'); ?>"></script>
    <!-- Flot -->
    <script src="<?php echo $this->url->get('gentelella-master/vendors/Flot/jquery.flot.js'); ?>"></script>
    <script src="<?php echo $this->url->get('gentelella-master/vendors/Flot/jquery.flot.pie.js'); ?>"></script>
    <script src="<?php echo $this->url->get('gentelella-master/vendors/Flot/jquery.flot.time.js'); ?>"></script>
    <script src="<?php echo $this->url->get('gentelella-master/vendors/Flot/jquery.flot.stack.js'); ?>"></script>
    <script src="<?php echo $this->url->get('gentelella-master/vendors/Flot/jquery.flot.resize.js'); ?>"></script>
    <!-- Flot plugins -->
    <script src="<?php echo $this->url->get('gentelella-master/vendors/flot.orderbars/js/jquery.flot.orderBars.js'); ?>"></script>
    <script src="<?php echo $this->url->get('gentelella-master/vendors/flot-spline/js/jquery.flot.spline.min.js'); ?>"></script>
    <script src="<?php echo $this->url->get('gentelella-master/vendors/flot.curvedlines/curvedLines.js'); ?>"></script>
    <!-- DateJS -->
    <script src="<?php echo $this->url->get('gentelella-master/vendors/DateJS/build/date.js'); ?>"></script>
    <!-- JQVMap -->
    <script src="<?php echo $this->url->get('gentelella-master/vendors/jqvmap/dist/jquery.vmap.js'); ?>"></script>
    <script src="<?php echo $this->url->get('gentelella-master/vendors/jqvmap/dist/maps/jquery.vmap.world.js'); ?>"></script>
    <script src="<?php echo $this->url->get('gentelella-master/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js'); ?>"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="<?php echo $this->url->get('gentelella-master/vendors/moment/min/moment.min.js'); ?>"></script>
    <script src="<?php echo $this->url->get('gentelella-master/vendors/bootstrap-daterangepicker/daterangepicker.js'); ?>"></script>

    <!-- Custom Theme Scripts -->
    <script src="<?php echo $this->url->get('gentelella-master/build/js/custom.min.js'); ?>"></script>
	
      </body>
</html>
