<div class="wrapper">
    <!-- Sidebar  -->
    <nav id="sidebar">
        <div class="sidebar-header">
            <h6>Welcome,</h6>
            <!-- <h3><?php echo implode("",$this->session->get('nama')); ?></h3> -->
            <!-- <h6><?php echo implode("",$this->session->get('nrp')); ?></h6> -->
            <h5><?php echo "Admin "; echo $this->session->get('nama_user'); ?></h5>
            <h6><?php echo $this->session->get('nrp'); ?></h6>
        </div>

        <ul class="list-unstyled components">
            <li>
            <?php
                echo $this->tag->linkTo([
                    "/admin/dashboard",
                    "Beranda",
                ]);
            ?>
            </li>
            <li class="active">
                <a href="#inventarisSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Inventaris</a>
                <ul class="collapse list-unstyled" id="inventarisSubmenu">
                    <li>
                        <?php
                            echo $this->tag->linkTo([
                                "/admin/listInv/".$this->session->isAdmin,
                                // "/admin/listInv/".$id,
                                "List",
                            ]);
                        ?>
                    </li>
                    <li>
                        <?php
                            echo $this->tag->linkTo([
                                "/admin/createInv/".$this->session->isAdmin,
                                "Tambah",
                            ]);
                        ?>
                    </li>
                    <li class="active">
                        <?php
                            echo $this->tag->linkTo([
                                "/admin/listpeminjamanInv/".$this->session->isAdmin,
                                "Konfirmasi Peminjaman",
                            ]);
                        ?>
                    </li>
                </ul>
            </li>
            </li>
            <li class="active">
                <a href="#ruanganSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Ruangan</a>
                <ul class="collapse list-unstyled" id="ruanganSubmenu">
                    <li>
                        <?php
                            echo $this->tag->linkTo([
                                "/admin/jadwalPemakaianRuangan/".$this->session->isAdmin,
                                "Jadwal",
                            ]);
                        ?>
                    </li>
                    <li class="active">
                        <?php
                            echo $this->tag->linkTo([
                                "/admin/listPermohonanRuangan/".$this->session->isAdmin,
                                "Konfirmasi Peminjaman",
                            ]);
                        ?>
                    </li>
                </ul>
            </li>
            <li class="active">
                <a href="#pcSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">PC</a>
                <ul class="collapse list-unstyled" id="pcSubmenu">
                    <li>
                        <?php
                            echo $this->tag->linkTo([
                                "/admin/listPC",
                                "List",
                            ]);
                        ?>
                    </li>
                    <li class="active">
                        <?php
                            echo $this->tag->linkTo([
                                "/admin/tambahpcpage",
                                "Tambah",
                            ]);
                        ?>
                    </li>
                    <li class="active">
                        <?php
                            echo $this->tag->linkTo([
                                "/admin/listReservasiPC/",
                                "Konfirmasi Peminjaman",
                            ]);
                        ?>
                    </li>
                </ul>
            </li>
        </ul>

        <ul class="list-unstyled CTAs">
            <li>
                <a href="/pengguna/logout" class="download">Logout</a>
            </li>
        </ul>
    </nav>

    <!-- Page Content  -->
    <div id="content">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <button type="button" id="sidebarCollapse" class="btn btn-info">
                    <i class="fas fa-align-left"></i>
                    <span>Menu</span>
                </button>
                <h3><?php echo $pagetitle; ?></h3>
            </div>
        </nav>

        <?php echo $this->getContent(); ?>
    </div>
</div>

<!-- <style>
.box{
      background-color: white;
      box-shadow: 0px 10px 8px #888888;
      border-radius: 15px;
      padding-right: 100px;
      text-align: right;
      padding-top: 20px;
      padding-bottom: 20px;
      margin:auto;
      float:none;
}
</style> -->