<div class="wrapper">
    <!-- Sidebar  -->
    <nav id="sidebar">
        <div class="sidebar-header">
            <h6>Welcome,</h6>
            <!-- <h3><?php //echo implode("",$this->session->get('nama')); ?></h3>
            <h6><?php //echo implode("",$this->session->get('nrp')); ?></h6> -->
            <h5><?php echo $this->session->get('nama_user'); ?></h5>
            <h6><?php echo $this->session->get('nrp'); ?></h6>
        </div>

        <ul class="list-unstyled components">
            <li>
            <?php
                echo $this->tag->linkTo([
                    "/mahasiswa/dashboard",
                    "Beranda",
                ]);
            ?>
            </li>
            <li>
            <?php
                echo $this->tag->linkTo([
                    "/mahasiswa/listInv/".$this->session->user_id,
                    "Pinjam Barang",
                ]);
            ?>
            </li>
            <li>
            <?php
                echo $this->tag->linkTo([
                    "/mahasiswa/reservasipcpage",
                    "Pinjam PC",
                ]);
            ?>
            </li>
            <li class="active">
                <a href="#ruanganSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Ruangan</a>
                <ul class="collapse list-unstyled" id="ruanganSubmenu">
                    <li>
                        <?php
                            echo $this->tag->linkTo([
                                "/mahasiswa/jadwalpemakaianruangan",
                                "Jadwal",
                            ]);
                        ?>
                    </li>
                    <li class="active">
                        <?php
                            echo $this->tag->linkTo([
                                "/mahasiswa/reservelabpage",
                                "Pinjam Ruangan",
                            ]);
                        ?>
                    </li>
                </ul>
            </li>
            
        </ul>

        <ul class="list-unstyled CTAs">
            <li>
                <a href="/pengguna/logout" class="download">Logout</a>
            </li>
        </ul>
    </nav>

    <!-- Page Content  -->
    <div id="content">

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">

                <button type="button" id="sidebarCollapse" class="btn btn-info">
                    <i class="fas fa-align-left"></i>
                    <span>Menu</span>
                </button>
                <h3><?php echo $pagetitle; ?></h3>
            </div>
        </nav>

        <?php echo $this->getContent(); ?>
    </div>
</div>